#!/bin/bash
clear
echo -e "\033[1;32m DESEJA ATUALIZAR O SSH-PRO ?\033[1;33m"
echo -e ""
read -p " Responda [s/n]: " resp
if [[ "$resp" = s || "$resp" = S ]];then
clear
fun_bar() {
	comando[0]="$1"
	comando[1]="$2"
	(
		[[ -e $HOME/fim ]] && rm $HOME/fim
		${comando[0]} -y >/dev/null 2>&1
		${comando[1]} -y >/dev/null 2>&1
		touch $HOME/fim
	) >/dev/null 2>&1 &
	tput civis
	echo -ne "     \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
	while true; do
		for ((i = 0; i < 18; i++)); do
			echo -ne "\033[1;31m#"
			sleep 0.1s
		done
		[[ -e $HOME/fim ]] && rm $HOME/fim && break
		echo -e "\033[1;33m]"
		sleep 1s
		tput cuu1
		tput dl1
		echo -ne "     \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
	done
	echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
	tput cnorm
}
fun_lixo () {
[[ -e wssecury.sh ]] && rm wssecury.sh && [[ -e wssecsl ]] &&  rm wssecsl && [[ -e wssec ]] && [[ -e wssec ]] && rm wssec && [[ -e script.sh ]] && rm script.sh && [[ -e rem.sh ]] && rm rem.sh && [[ -e add.sh ]] && rm add.sh && [[ -e botteste.sh ]] && rm botteste.sh && [[ -e install ]] && rm install && apt clean && apt autoclean && apt full-upgrade -y
}
fun_att () {
[[ -e Plus ]] && rm Plus
wget raw.githubusercontent.com/zxlordxz/cvpn/main/script/Plus && chmod 777 Plus
}
clear
echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mREMOVENDO LIXO \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
echo ""
fun_bar 'fun_lixo'
clear
echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mINICIANDO ATUALIZAÇÃO \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
echo""
fun_bar 'fun_att'
./Plus
fi