#!/bin/bash
clear
check_installed() {
    if [ -f "/usr/lib/checkany/checkany.py" ]; then
        return 0  # Já instalado
    else
        return 1  # Não instalado
    fi
}
fun_bar() {
	comando[0]="$1"
	comando[1]="$2"
	(
		[[ -e $HOME/fim ]] && rm $HOME/fim
		${comando[0]} -y >/dev/null 2>&1
		${comando[1]} -y >/dev/null 2>&1
		touch $HOME/fim
	) >/dev/null 2>&1 &
	tput civis
	echo -ne "     \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
	while true; do
		for ((i = 0; i < 18; i++)); do
			echo -ne "\033[1;31m#"
			sleep 0.1s
		done
		[[ -e $HOME/fim ]] && rm $HOME/fim && break
		echo -e "\033[1;33m]"
		sleep 1s
		tput cuu1
		tput dl1
		echo -ne "     \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
	done
	echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
	tput cnorm
    }
    fun_install () {
	bash <(wget -qO- https://raw.githubusercontent.com/UlekBR/UlekCheckUser/main/install.sh)
	}

clear
figlet "CHECKUSER" | lolcat
    echo -e "\033[0;36m╔═══════════════════════════•⊱✦⊰•═══════════════════════════╗\033[0m"
	echo -e "\033[1;37m   DEPOIS QUE INSTALAR, ENTRE NO MENU\033[0m"
	echo -e "\033[0;36m° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° °\033[0m"
echo -e "\033[0;31m   [\033[1;36m01\033[0;31m] \033[1;37m• \033[1;37mINSTALAR\033[0m"
echo -e "\033[0;31m   [\033[1;36m02\033[0;31m] \033[1;37m• \033[1;37mMENU\033[0m"
    echo -e "\033[0;36m° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° °\033[0m"
    echo -e "\033[0;31m   [\033[1;36m00\033[0;31m] \033[1;37m• \033[1;37mVOLTAR  \033[1;32m<\033[1;33m<\033[1;31m< \033[0m"
    echo -e "\033[0;36m╚═══════════════════════════•⊱✦⊰•═══════════════════════════╝\033[0m"
tput civis
echo -ne "\033[1;31m➤ \033[1;32mESCOLHA OPÇÃO DESEJADA\033[1;33m\033[1;31m\033[1;37m : "
read x
tput cnorm
clear
case $x in
1 | 01)
    clear
	echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mINSTALANDO CHECKUSER\033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
	echo ""
	fun_bar 'fun_install'
	sleep 1s
	echo -e "\033[1;33mINSTALADO, ENTRE NO MENU!\033[0m"
	checkers
    ;;
2 | 02)
    clear
	ulekCheckuser
	checkers
    ;;
0 | 00)
    clear
    menu
    ;;
*)
    echo -e "\033[1;31mOpcao invalida!\033[0m"
	checkers
    ;;
esac
sleep 2
