#!/bin/bash
    clear
	fun_bar() {
	comando[0]="$1"
	comando[1]="$2"
	(
		[[ -e $HOME/fim ]] && rm $HOME/fim
		${comando[0]} -y >/dev/null 2>&1
		${comando[1]} -y >/dev/null 2>&1
		touch $HOME/fim
	) >/dev/null 2>&1 &
	tput civis
	echo -ne "     \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
	while true; do
		for ((i = 0; i < 18; i++)); do
			echo -ne "\033[1;31m#"
			sleep 0.1s
		done
		[[ -e $HOME/fim ]] && rm $HOME/fim && break
		echo -e "\033[1;33m]"
		sleep 1s
		tput cuu1
		tput dl1
		echo -ne "     \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
	done
	echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
	tput cnorm
    }
    fun_badpro () {
    screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:7400 --max-clients 10000 --max-connections-for-client 8 --client-socket-sndbuf 10000 --udp-mtu 9000
    screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:7500 --max-clients 10000 --max-connections-for-client 8 --client-socket-sndbuf 10000 --udp-mtu 9000
	rm -f /etc/systemd/system/bad7400-7500.service && curl -s -L -o /etc/systemd/system/bad7400-7500.service https://github.com/vmell0/pro/raw/main/script/services/bad7400-7500.service && chmod +x /etc/systemd/system/bad7400-7500.service && sudo systemctl daemon-reload && sudo systemctl enable bad7400-7500.service
    }
    clear
    echo -e "\E[44;1;37m                    🚀 BADVPN 🚀                   \E[0m"
    echo -e "\033[0;36m╔══════════════════════•⊱✦⊰•══════════════════════╗\033[0m"
	if ps x | grep -w udpvpn | grep -v grep 1>/dev/null 2>/dev/null; then
        echo -e "\033[1;33m   PORTA ABERTA\033[1;37m: \033[1;32m$(netstat -nplt | grep 'badvpn-ud' | awk {'print $4'} | cut -d: -f2 | xargs)"
    else
        sleep 0.1
    fi
    var_sks1=$(ps x | grep "udpvpn"|grep -v grep > /dev/null && echo -e "\033[1;32m◉ " || echo -e "\033[1;31m○ ")
	echo ""
    echo -e "\033[0;31m   [\033[1;36m01\033[0;31m] \033[1;37m• \033[1;37mBADVPN PRO $stsu\033[0m"
    echo -e "\033[0;31m   [\033[1;36m02\033[0;31m] \033[1;37m• \033[1;37mATIVAR PORTAS 7400, 7500\033[0m"
    echo -e "\033[0;31m   [\033[1;36m00\033[0;31m] \033[1;37m• \033[1;37mVOLTAR  \033[1;32m<\033[1;33m<\033[1;31m< \033[0m"
    echo -e "\033[0;36m╚══════════════════════•⊱✦⊰•══════════════════════╝\033[0m"
			tput civis
			echo -ne "\033[1;31m➤ \033[1;32mDIGITE A OPÇÃO\033[1;33m\033[1;31m\033[1;37m: ";
			read x
			tput cnorm
			clear
			case $x in
			1 | 01)
		    clear
            badpro
			menub
            ;;
			2 | 02)
			clear
            echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mATIVANDO PORTAS 7400, 7500 \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
            echo ""
            fun_bar 'fun_badpro'
			menub
            ;;
			0 | 00)
			clear
			menu
			;;
			*)
			echo -e "\033[1;31mOpcao invalida !\033[0m"
			sleep 2
			;;
			esac
		done
	}
	menub
}
