#!/bin/bash
    clear
    fun_bar() {
	comando[0]="$1"
	comando[1]="$2"
	(
		[[ -e $HOME/fim ]] && rm $HOME/fim
		${comando[0]} -y >/dev/null 2>&1
		${comando[1]} -y >/dev/null 2>&1
		touch $HOME/fim
	) >/dev/null 2>&1 &
	tput civis
	echo -ne "     \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
	while true; do
		for ((i = 0; i < 18; i++)); do
			echo -ne "\033[1;31m#"
			sleep 0.1s
		done
		[[ -e $HOME/fim ]] && rm $HOME/fim && break
		echo -e "\033[1;33m]"
		sleep 1s
		tput cuu1
		tput dl1
		echo -ne "     \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
	done
	echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
	tput cnorm
    }
    fun_port80 () {
	curl -s -L -o /etc/systemd/system/websecty80.service https://github.com/zxlordxz/cvpn/raw/main/script/services/websecty80.service && chmod +x /etc/systemd/system/websecty80.service && sudo systemctl daemon-reload && sudo systemctl start websecty80.service && sudo systemctl enable websecty80.service
	}
	fun_lixo80 () {
	rm -f /etc/systemd/system/websecty80.service && sudo systemctl disable --now websecty80.service && sudo systemctl stop websecty80.service && sudo systemctl daemon-reload
	}
	fun_port8080 () {
	curl -s -L -o /etc/systemd/system/websecty8080.service https://github.com/zxlordxz/cvpn/raw/main/script/services/websecty8080.service && chmod +x /etc/systemd/system/websecty8080.service && sudo systemctl daemon-reload && sudo systemctl start websecty8080.service && sudo systemctl enable websecty8080.service
	}
	fun_lixo8080 () {
	rm -f /etc/systemd/system/websecty8080.service && sudo systemctl disable --now websecty8080.service && sudo systemctl stop websecty8080.service && sudo systemctl daemon-reload
	}
    clear
    echo -e "\E[44;1;37m               🚀 SECURITY 🚀              \E[0m"
    echo -e "\033[0;36m╔══════════════════•⊱✦⊰•══════════════════╗\033[0m"
    [[ "$(netstat -tlpn | grep 'WebSocket' | wc -l)" != '0' ]] && {
				echo -e "\033[1;32m   PORTA ATIVA: \033[1;37m$(netstat -nplt | grep 'WebSocket' | awk -F ":" {'print $4'} | xargs)"
				echo -e "\033[0;36m° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° °\033[0m"
			} || {
				sks='\033[1;31mOFF'
			}
    echo -e "\033[0;31m   [\033[1;36m01\033[0;31m] \033[1;37m• \033[1;37mATIVAR PORTA 80\033[0m"
	echo -e "\033[0;31m   [\033[1;36m02\033[0;31m] \033[1;37m• \033[1;37mATIVAR PORTA 8080\033[0m"
	echo -e "\033[0;36m° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° °\033[0m"
	echo -e "\033[0;31m   [\033[1;36m03\033[0;31m] \033[1;37m• \033[1;37mDESATIVAR PORTA 80\033[0m"
	echo -e "\033[0;31m   [\033[1;36m04\033[0;31m] \033[1;37m• \033[1;37mDESATIVAR PORTA 8080\033[0m"
	echo -e "\033[0;36m° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° °\033[0m"
    echo -e "\033[0;31m   [\033[1;36m00\033[0;31m] \033[1;37m• \033[1;37mVOLTAR \033[1;32m<\033[1;33m<\033[1;31m< \033[0m"
    echo -e "\033[0;36m╚══════════════════•⊱✦⊰•══════════════════╝\033[0m"
			tput civis
			echo -ne "\033[1;31m➤ \033[1;32mESCOLHA OPÇÃO DESEJADA\033[1;33m\033[1;31m\033[1;37m : ";
			read x
			tput cnorm
			clear
			case $x in
			1 | 01)
			clear
			echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mATIVANDO SECURITY NA PORTA 80 \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
			echo ""
			fun_bar 'fun_port80'
			menusec
			;;
			2 | 02)
			clear
			echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mATIVAR SECURITY PORTA 8080 \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
			echo ""
			fun_bar 'fun_port8080'
			menusec
			;;
		    3 | 03)
			clear
			echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mDESATIVANDO SECURITY NA PORTA 80 \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
			echo ""
			fun_bar 'fun_lixo80'
			menusec
			;;
			4 | 04)
			clear
			echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mDESATIVANDO SECURITY PORTA 8080 \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
			echo ""
			fun_bar 'fun_lixo8080'
			menusec
			;;
			0 | 00)
			clear
			conexao
			;;
			*)
			echo -e "\033[1;31mOpcao invalida !\033[0m"
			sleep 2
			;;
			esac
		done
	}
	menusec
}
